### ISSUE TITLE
Random QR Code Generation

### ISSUE THREAD

**Issue by nums11** [rcos/Venue2#12]
Instructor should be able to generate random QR Codes for every event.

May need to figure out how to add a QR code as a variable to the Event model

**Comment by TheStopsign** [comment]
QR Codes are 4000 char. So what I'm thinking, instead of generating a random QR Code,

- Professor randomly generate a 4000 character attendance code
- The instructor toggles the show QR button
- Students read the QR code (IN the webapp, we dont want students sharing links)
- Check the decoded qr-code string against all active events (or however we want to orchestrate that)

**Comment by nums11** [comment]
Implemented in #17
