### ISSUE TITLE
Add automatic Geo Fencing

### ISSUE THREAD

**Issue by nums11** [rcos/Venue2#14]
- Instructor should be able to input a location (like DCC) and have the geofence be automatically created around the location
- Could even be specified to room (e.g. DCC 308)

**Comment by elihschiff** [comment]
I would personally advise against adding such a strict geofence such as a specific lecture hall like DCC308. Because you are inside, gps is not super accurate and can drift pretty far which could cause a user to be moved outside such a strict geofence even when they are there in person. Additionally, many devices dont have a gps and rely on wifi to try and figure out their location. This often does not work or when it does is not very accurate which would mean somebody on a computer without a gps might be marked as not inside the geofence even when they are. https://www.quora.com/How-does-the-indicated-site-get-my-location-with-a-laptop-with-no-GPS-It-returns-close-to-my-exact-address
